# Spring Cloud Config
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# Server Port
server.port=8090

# Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# GestoPago Service Configuration
gestopago.auth.url=https://gestopago.portalventas.net
gestopago.auth.id-distribuidor=83
gestopago.auth.codigo-dispositivo=GPS83-TPV-17
gestopago.auth.password=12345678
gestopago.auth.refresh-rate-ms=3600000

# GestoPago Product List Service Configuration
# URL base para el servicio de productos de GestoPago
gestopago.products.url=https://gestopago.portalventas.net
# Token Bearer configurable para autenticación con el servicio externo
gestopago.products.bearer-token=qmzAAEYFmqQbIT/Ktxme8Akih4Md6cXf9hTHKjfO626aEN8GrvSLaA9CJP3Q1UI5bL6/tDk+nsTwmGoUwm3VR+LPbGaB13DSSR2d+wUdceQX/1eKixyP0WU7GxdyJakm0uC+Gf5C9g/4LkTdAlwNFA==
# Tiempos de espera para el cliente HTTP Feign (en ms)
gestopago.products.connect-timeout=5000
gestopago.products.read-timeout=10000

# Redis Cache Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000
spring.cache.type=redis
spring.cache.redis.time-to-live=86400000

# Cron Programado: Se ejecuta diariamente a las 6:00 AM (0 segundos, 0 minutos, 6 horas, cualquier día)
//gestopago.cron.productos=0 0 6 * * ?
gestopago.cron.productos=*/02 * * * * ?

