-- =============================================================================
-- MIGRACIÓN V2: ESTRUCTURA DEL SISTEMA BANCARIO Y ONBOARDING DE CLIENTES
-- =============================================================================
-- Proyecto: Onboarding de Clientes Personas Físicas y Autenticación
-- Base de datos: PostgreSQL
--
-- V1 PREEXISTENTE:
--   gestopago_tokens
--
-- Esta migración define:
--   1. paises
--   2. estado_civil
--   3. clientes
--   4. domicilio
--   5. informacion_laboral
--   6. estatus_cuenta
--   7. cuentas
--   8. saldos
--   9. datos_biometricos
--  10. usuarios
--  11. sesiones
-- =============================================================================


-- =============================================================================
-- 1. TABLA: paises
-- Catálogo de países.
-- =============================================================================

CREATE TABLE IF NOT EXISTS paises (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              TEXT NOT NULL,
    codigo_iso          TEXT NOT NULL,
    activo              BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_paises_nombre
        UNIQUE (nombre),

    CONSTRAINT uq_paises_codigo_iso
        UNIQUE (codigo_iso)
);


-- =============================================================================
-- 2. TABLA: estado_civil
-- Catálogo de estados civiles.
-- =============================================================================

CREATE TABLE IF NOT EXISTS estado_civil (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion         TEXT NOT NULL,
    activo              BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_estado_civil_descripcion
        UNIQUE (descripcion)
);


-- =============================================================================
-- 3. TABLA: clientes
-- Información personal y de contacto del cliente.
-- =============================================================================

CREATE TABLE IF NOT EXISTS clientes (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nombre                  TEXT NOT NULL,
    segundo_nombre          TEXT,
    apellido_paterno        TEXT NOT NULL,
    apellido_materno        TEXT NOT NULL,

    fecha_nacimiento        DATE NOT NULL,

    curp                    TEXT NOT NULL,
    rfc                     TEXT NOT NULL,

    sexo                    TEXT NOT NULL,

    nacionalidad_id         BIGINT NOT NULL,
    estado_civil_id         BIGINT NOT NULL,

    correo                  TEXT NOT NULL,
    telefono_movil          TEXT NOT NULL,
    telefono_alternativo    TEXT,

    activo                  BOOLEAN NOT NULL DEFAULT TRUE,

    fecha_creacion          TIMESTAMP NOT NULL DEFAULT NOW(),
    fecha_actualizacion     TIMESTAMP NOT NULL DEFAULT NOW(),
    fecha_baja              TIMESTAMP,

    CONSTRAINT uq_clientes_curp
        UNIQUE (curp),

    CONSTRAINT uq_clientes_rfc
        UNIQUE (rfc),

    CONSTRAINT uq_clientes_correo
        UNIQUE (correo),

    CONSTRAINT fk_clientes_nacionalidad
        FOREIGN KEY (nacionalidad_id)
        REFERENCES paises(id),

    CONSTRAINT fk_clientes_estado_civil
        FOREIGN KEY (estado_civil_id)
        REFERENCES estado_civil(id),

    CONSTRAINT chk_clientes_curp_longitud
        CHECK (LENGTH(curp) = 18),

    CONSTRAINT chk_clientes_rfc_longitud
        CHECK (LENGTH(rfc) IN (12, 13)),

    CONSTRAINT chk_clientes_telefono_movil
        CHECK (telefono_movil ~ '^[0-9]{10}$'),

    CONSTRAINT chk_clientes_correo_longitud
        CHECK (LENGTH(correo) <= 100)
);


-- =============================================================================
-- 4. TABLA: domicilio
-- Domicilio principal del cliente.
-- Relación: CLIENTES 1:1 DOMICILIO
-- =============================================================================

CREATE TABLE IF NOT EXISTS domicilio (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cliente_id          BIGINT NOT NULL,

    calle               TEXT NOT NULL,
    numero_exterior     TEXT NOT NULL,
    numero_interior     TEXT,

    colonia             TEXT NOT NULL,
    municipio            TEXT NOT NULL,
    estado              TEXT NOT NULL,
    codigo_postal       TEXT NOT NULL,

    pais_id             BIGINT NOT NULL,

    CONSTRAINT uq_domicilio_cliente
        UNIQUE (cliente_id),

    CONSTRAINT fk_domicilio_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES clientes(id),

    CONSTRAINT fk_domicilio_pais
        FOREIGN KEY (pais_id)
        REFERENCES paises(id),

    CONSTRAINT chk_domicilio_codigo_postal
        CHECK (codigo_postal ~ '^[0-9]{5}$')
);


-- =============================================================================
-- 5. TABLA: informacion_laboral
-- Información laboral del cliente.
-- Relación: CLIENTES 1:1 INFORMACION_LABORAL
-- =============================================================================

CREATE TABLE IF NOT EXISTS informacion_laboral (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cliente_id          BIGINT NOT NULL,

    ocupacion           TEXT NOT NULL,
    empresa             TEXT NOT NULL,
    ingreso_mensual     NUMERIC(15,2) NOT NULL,

    CONSTRAINT uq_informacion_laboral_cliente
        UNIQUE (cliente_id),

    CONSTRAINT fk_informacion_laboral_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES clientes(id),

    CONSTRAINT chk_ingreso_mensual
        CHECK (ingreso_mensual > 0)
);


-- =============================================================================
-- 6. TABLA: estatus_cuenta
-- Catálogo de estados de las cuentas bancarias.
-- =============================================================================

CREATE TABLE IF NOT EXISTS estatus_cuenta (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              TEXT NOT NULL,
    descripcion         TEXT,
    activo              BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_estatus_cuenta_nombre
        UNIQUE (nombre)
);


-- =============================================================================
-- 7. TABLA: cuentas
-- Cuentas bancarias pertenecientes a los clientes.
-- Relación: CLIENTES 1:N CUENTAS
-- =============================================================================

CREATE TABLE IF NOT EXISTS cuentas (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cliente_id          BIGINT NOT NULL,
    numero_cuenta       TEXT NOT NULL,
    estatus_cuenta_id   BIGINT NOT NULL,

    fecha_creacion      TIMESTAMP NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_cuentas_numero_cuenta
        UNIQUE (numero_cuenta),

    CONSTRAINT fk_cuentas_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES clientes(id),

    CONSTRAINT fk_cuentas_estatus
        FOREIGN KEY (estatus_cuenta_id)
        REFERENCES estatus_cuenta(id)
);


-- =============================================================================
-- 8. TABLA: saldos
-- Saldo monetario actual de cada cuenta.
-- Relación: CUENTAS 1:1 SALDOS
-- =============================================================================

CREATE TABLE IF NOT EXISTS saldos (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cuenta_id           BIGINT NOT NULL,

    saldo_disponible    NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    saldo_contable      NUMERIC(15,2) NOT NULL DEFAULT 0.00,

    moneda              TEXT NOT NULL DEFAULT 'MXN',

    fecha_actualizacion TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_saldos_cuenta
        UNIQUE (cuenta_id),

    CONSTRAINT fk_saldos_cuenta
        FOREIGN KEY (cuenta_id)
        REFERENCES cuentas(id),

    CONSTRAINT chk_saldos_disponible
        CHECK (saldo_disponible >= 0),

    CONSTRAINT chk_saldos_contable
        CHECK (saldo_contable >= 0)
);


-- =============================================================================
-- 9. TABLA: datos_biometricos
-- Información biométrica asociada al cliente.
-- =============================================================================

CREATE TABLE IF NOT EXISTS datos_biometricos (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cliente_id          BIGINT NOT NULL,

    CONSTRAINT fk_datos_biometricos_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES clientes(id)
);


-- =============================================================================
-- 10. TABLA: usuarios
-- Credenciales de acceso asociadas a los clientes.
-- =============================================================================

CREATE TABLE IF NOT EXISTS usuarios (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    cliente_id          BIGINT NOT NULL,
    username            TEXT NOT NULL,
    password_hash       TEXT NOT NULL,
    activo              BOOLEAN NOT NULL DEFAULT TRUE,
    intentos_fallidos   INTEGER NOT NULL DEFAULT 0,
    bloqueado           BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_ultimo_acceso TIMESTAMP,

    fecha_creacion      TIMESTAMP NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMP NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_usuarios_cliente
        UNIQUE (cliente_id),

    CONSTRAINT uq_usuarios_username
        UNIQUE (username),

    CONSTRAINT fk_usuarios_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES clientes(id)
        ON DELETE CASCADE
);


-- =============================================================================
-- 11. TABLA: sesiones
-- Control de sesiones y tokens.
-- =============================================================================

CREATE TABLE IF NOT EXISTS sesiones (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    usuario_id              BIGINT NOT NULL,
    token_sesion            TEXT NOT NULL,
    activa                  BOOLEAN NOT NULL DEFAULT TRUE,
    ip_origen               TEXT,
    user_agent              TEXT,

    fecha_inicio            TIMESTAMP NOT NULL DEFAULT NOW(),
    fecha_ultima_actividad  TIMESTAMP NOT NULL DEFAULT NOW(),
    fecha_expiracion        TIMESTAMP NOT NULL,

    CONSTRAINT uq_sesiones_token
        UNIQUE (token_sesion),

    CONSTRAINT fk_sesiones_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios(id)
        ON DELETE CASCADE
);


-- =============================================================================
-- ÍNDICES ADICIONALES
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_domicilio_cliente
    ON domicilio(cliente_id);

CREATE INDEX IF NOT EXISTS idx_informacion_laboral_cliente
    ON informacion_laboral(cliente_id);

CREATE INDEX IF NOT EXISTS idx_cuentas_cliente
    ON cuentas(cliente_id);

CREATE INDEX IF NOT EXISTS idx_cuentas_estatus
    ON cuentas(estatus_cuenta_id);

CREATE INDEX IF NOT EXISTS idx_clientes_activo
    ON clientes(activo);

CREATE INDEX IF NOT EXISTS idx_clientes_fecha_creacion
    ON clientes(fecha_creacion);

CREATE INDEX IF NOT EXISTS idx_saldos_cuenta
    ON saldos(cuenta_id);

CREATE INDEX IF NOT EXISTS idx_biometria_cliente
    ON datos_biometricos(cliente_id);

CREATE INDEX IF NOT EXISTS idx_usuarios_username
    ON usuarios(username);

CREATE INDEX IF NOT EXISTS idx_usuarios_cliente
    ON usuarios(cliente_id);

CREATE INDEX IF NOT EXISTS idx_sesiones_token
    ON sesiones(token_sesion);
